import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import Gradientdiv from "@/components/ui/Gradientdiv";

const inter = Inter({ subsets: ["latin"] });

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={manrope.className} lang="en">
      <body className=" h-screen w-screen  bg-bg_primary text-white ">
        <Gradientdiv className=" h-full w-full px-16">{children}</Gradientdiv>
      </body>
    </html>
  );
}
